### ISSUE TITLE
Android Screen remains black when starting the app

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#360]
Flutter crashes on first startup (Current Build on commit 481).

It seems to be related to the notification system.

Logcat error report:

```
07-05 15:07:12.397 19694 14965 I libqaul : start initializing libqaul
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: calling checked jni method: GetArrayLength
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: looking up jni method GetArrayLength
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: found jni method
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: checking for exception
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: calling unchecked jni method: ExceptionCheck
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: looking up jni method ExceptionCheck
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: found jni method
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: no exception found
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: calling unchecked jni method: GetByteArrayRegion
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: looking up jni method GetByteArrayRegion
07-05 15:07:12.397 19694 19694 V jni::wrapper::jnienv: found jni method
07-05 15:07:12.397 19694 14965 E libqaul::storage::con..: no configuration file found, creating one.
07-05 15:07:12.398 19694 14948 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: Cannot fire new event. Controller is already firing an event
07-05 15:07:12.398 19694 14948 E flutter : #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243)
07-05 15:07:12.398 19694 14948 E flutter : #1      Logger._publish (package:logging/src/logger.dart:276)
07-05 15:07:12.398 19694 14948 E flutter : #2      Logger.log (package:logging/src/logger.dart:198)
07-05 15:07:12.398 19694 14948 E flutter : #3      Logger.severe (package:logging/src/logger.dart:258)
07-05 15:07:12.398 19694 14948 E flutter : #4      main.<anonymous closure> (package:qaul_ui/main.dart:30)
07-05 15:07:12.398 19694 14948 E flutter : #5      _rootRunBinary (dart:async/zone.dart:1450)
07-05 15:07:12.398 19694 14948 E flutter : #6      _CustomZone.runBinary (dart:async/zone.dart:1342)
07-05 15:07:12.398 19694 14948 E flutter : #7      runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1832)
07-05 15:07:12.398 19694 14948 E flutter : #8      _Zone._processUncaughtError (dart:async/zone.dart:1109)
07-05 15:07:12.398 19694 14948 E flutter : #9      _CustomZone.handleUncaughtError (dart:async/zone.dart:1312)
07-05 15:07:12.398 19694 14948 E flutter : #10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1246)
07-05 15:07:12.398 19694 14948 E flutter : #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
07-05 15:07:12.398 19694 14948 E flutter : #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
07-05 15:07:12.398 19694 14948 E flutter : #13     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377)
07-05 15:07:12.398 19694 14948 E flutter : #14     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244)
07-05 15:07:12.398 19694 14948 E flutter : #15     Logger._publish (package:logging/src/logger.dart:276)
07-05 15:07:12.398 19694 14948 E flutter : #16     Logger.log (package:logging/src/logger.dart:200)
07-05 15:07:12.398 19694 14948 E flutter : #17     Logger.shout (package:logging/src/logger.dart:265)
07-05 15:07:12.398 19694 14948 E flutter : #18     NeatPeriodicTaskScheduler._claimAndRun (package:neat_periodic_task/neat_periodic_task.dart:301)
07-05 15:07:12.398 19694 14948 E flutter : <asynchronous suspension>
07-05 15:07:12.398 19694 14948 E flutter : #19     NeatPeriodicTaskScheduler._iteration (package:neat_periodic_task/neat_periodic_task.dart:275)
07-05 15:07:12.398 19694 14948 E flutter : <asynchronous suspension>
07-05 15:07:12.398 19694 14948 E flutter : #20     NeatPeriodicTaskScheduler._loop (package:neat_periodic_task/neat_periodic_task.dart:201)
07-05 15:07:12.398 19694 14948 E flutter : <asynchronous suspension>
07-05 15:07:12.398 19694 14948 E flutter : 
07-05 15:07:12.399 19694 14948 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: Cannot fire new event. Controller is already firing an event
07-05 15:07:12.399 19694 14948 E flutter : #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243)
07-05 15:07:12.399 19694 14948 E flutter : #1      Logger._publish (package:logging/src/logger.dart:276)

```

**Comment by brenodt** [comment]
I can confirm that the new [rust release](https://github.com/qaul/qaul.net/releases/tag/v0.3.0-rust) fixed the issue. Closing this for now.
