### ISSUE TITLE
BluetoothGatt Crash after BLE message is sent

### ISSUE THREAD

**Issue by MathJud** [qaul/qaul.net#523]
When libqaul tries to send a message to a newly discovered device, there is a `BluetoothGatt` crash.

These are the logs:

```
01-24 13:33:07.741 14949 15488 E qaul-blemodule BleService:  onServiceDiscovered : 51:60:83:0D:4B:04
01-24 13:33:07.741 14949 15488 E qaul-blemodule BleService:  onDescriptorWrite : 51:60:83:0D:4B:04
01-24 13:33:07.741 14949 15488 D qaul-blemodule BleActor: readServiceData : serUUID : 99E91399-80ED-4943-9BCB-39C532A76023, charUUID:99E91401-80ED-4943-9BCB-39C532A76023
01-24 13:33:07.753  7390  7390 D IHansComunication: HansComunication::configCheckedUid-- 10389, type = 0
01-24 13:33:07.753  7390  7390 D IHansComunication: HANS sendMessageToKernel: threadId = 526219459760, netLinkSetup = 1, type = FROZEN_TRANS, targetUid = 10389, pkgCmd = PKG_CMD_MAX
01-24 13:33:07.757 28759 28992 I bt_stack: [INFO:gatt_main.cc(1640)] gatt_data_process op_code = 11, msg_len = 17
01-24 13:33:07.762 14949 15488 D qaul-blemodule BleActor: onCharacteristicRead : 99e91401-80ed-4943-9bcb-39c532a76023 , data : 0598F7B34B75ADCB7396381012BB9501AF
01-24 13:33:07.763 14949 15488 I qaul-blemodule BleWrapperClass: sendResponse()
01-24 13:33:07.763 14949 15488 D BluetoothGatt: refresh() - device: 51:60:83:0D:4B:04
01-24 13:33:07.765 14949 15488 D BluetoothGatt: cancelOpen() - device: 51:60:83:0D:4B:04
01-24 13:33:07.766 28759 28992 I bt_stack: [INFO:gatt_api.cc(887)] GATTC_Discover conn_id=0x010c, disc_type=1, s_handle=0x0001, e_handle=0xffff
01-24 13:33:07.768 28759 28839 E bt_btif_gattc: btif_gattc_upstreams_evt: Unhandled event (8)!
01-24 13:33:07.768 28759 28992 I bt_stack: [INFO:gatt_api.cc(1550)] GATT_Disconnect conn_id=0x010c
01-24 13:33:07.768 28759 28992 I bt_stack: [INFO:bta_gattc_act.cc(677)] Local close event client_if:  conn_id: 268 reason: 0
01-24 13:33:07.768 28759 28992 I bt_stack: [INFO:bta_gattc_act.cc(347)] Cancel GATT client background connection
01-24 13:33:07.768 28759 28992 E bt_stack: [ERROR:bta_gattc_utils.cc(458)] bta_gattc_mark_bg_conn unable to find the bg connection mask for bd_addr=51:60:83:0d:4b:04
01-24 13:33:07.769 14949 14998 I libqaul::connections:..: BLE device discovered: [5, 152, 247, 179, 75, 117, 173, 203, 115, 150, 56, 16, 18, 187, 149, 1, 175]
01-24 13:33:07.771 14949 14998 I libqaul::connections:..: BLE discovered Node ID unknown
01-24 13:33:07.771 14949 14998 I libqaul::connections:..: BLE send identity information
01-24 13:33:07.771 14949 14998 I libqaul::connections:..: BLE send message to [5, 152, 247, 179, 75, 117, 173, 203, 115, 150, 56, 16, 18, 187, 149, 1, 175]
01-24 13:33:07.771 14949 15488 W BluetoothGatt: Unhandled exception in callback
01-24 13:33:07.771 14949 15488 W BluetoothGatt: java.lang.NullPointerException
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at net.qaul.ble.core.BleActor.disConnectedDevice(BleActor.kt:46)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at net.qaul.ble.core.BleActor.access$disConnectedDevice(BleActor.kt:20)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at net.qaul.ble.core.BleActor$mGattCallback$1.onCharacteristicRead(BleActor.kt:164)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt$1$6.run(BluetoothGatt.java:405)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:823)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:47)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at android.bluetooth.BluetoothGatt$1.onCharacteristicRead(BluetoothGatt.java:399)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:255)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at android.os.Binder.execTransactInternal(Binder.java:1226)
01-24 13:33:07.771 14949 15488 W BluetoothGatt: 	at android.os.Binder.execTransact(Binder.java:1163)
01-24 13:33:07.778 14949 14998 I ===libqaul===: This was called from libqaul.  :-)
01-24 13:33:07.779 14949 14949 I qaul-blemodule BleWrapperClass: DIRECT_SEND
01-24 13:33:07.780 14949 14949 E qaul-blemodule BleActor: connectDevice : 51:60:83:0D:4B:04
01-24 13:33:07.782 14949 14949 D BluetoothGatt: connect() - device: 51:60:83:0D:4B:04, auto: false, eattSupport: false
01-24 13:33:07.782 14949 14949 D BluetoothGatt: registerApp()
01-24 13:33:07.782 14949 14949 D BluetoothGatt: registerApp() - UUID=725480be-2a67-450f-9b63-70bd75137fac
01-24 13:33:07.783 14949 15488 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=12 device=51:60:83:0D:4B:04
01-24 13:33:07.784 28759 28992 I bt_stack: [INFO:gatt_main.cc(1640)] gatt_data_process op_code = 17, msg_len = 13
01-24 13:33:07.784 14949 15488 E qaul-blemodule BleActor: onConnectionStateChange: STATE_DISCONNECTED
01-24 13:33:07.784 14949 15488 D BluetoothGatt: refresh() - device: 51:60:83:0D:4B:04
01-24 13:33:07.785 28759 28992 I bt_stack: [INFO:gatt_api.cc(1223)] GATT_Register 211ad3df-a154-5cab-0a8e-1b448b8c4240
01-24 13:33:07.785 28759 28992 I bt_stack: [INFO:gatt_api.cc(1244)] allocated gatt_if=13
01-24 13:33:07.785 14949 15488 D BluetoothGatt: close()
01-24 13:33:07.785 14949 15488 D BluetoothGatt: unregisterApp() - mClientIf=12
01-24 13:33:07.786 14949 15333 D BluetoothGatt: onClientRegistered() - status=0 clientIf=13
01-24 13:33:07.787 28759 28839 D bt_btif_config: btif_get_address_type: Device [51:60:83:0d:4b:04] address type 1
01-24 13:33:07.787 28759 28839 D bt_btif_config: btif_get_device_type: Device [51:60:83:0d:4b:04] type 2
01-24 13:33:07.788 28759 28992 I bt_stack: [INFO:gatt_api.cc(1413)] GATT_Connect gatt_if=13, address=51:60:83:0d:4b:04 is_direct 1
01-24 13:33:07.788 28759 28992 E bt_stack: [ERROR:bta_gattc_cache.cc(753)] bta_gattc_cache_load: can't open GATT cache file /data/misc/bluetooth/gatt_cache_5160830d4b04 for reading, error: No such file or directory
01-24 13:33:07.788 28759 28992 I bt_stack: [INFO:gatt_api.cc(887)] GATTC_Discover conn_id=0x010d, disc_type=1, s_handle=0x0001, e_handle=0xffff
01-24 13:33:07.794 14949 14949 D qaul-blemodule BleService: device : D0:03:4B:40:D0:30
01-24 13:33:07.794 28759 28992 I bt_stack: [INFO:gatt_main.cc(1640)] gatt_data_process op_code = 17, msg_len = 21
01-24 13:33:07.794 28759 28992 I bt_stack: [INFO:gatt_api.cc(887)] GATTC_Discover conn_id=0x010d, disc_type=3, s_handle=0x0028, e_handle=0xffff
01-24 13:33:07.796 14949 14949 D qaul-blemodule BleService: device : D0:03:4B:40:D0:30
01-24 13:33:07.798 14949 15488 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=13 device=51:60:83:0D:4B:04
01-24 13:33:07.798 14949 15488 E qaul-blemodule BleActor: onConnectionStateChange: STATE_CONNECTED
01-24 13:33:07.798 14949 15488 E qaul-blemodule BleService:  onConnected : 51:60:83:0D:4B:04
01-24 13:33:07.798 14949 15488 D BluetoothGatt: discoverServices() - device: 51:60:83:0D:4B:04
01-24 13:33:07.809 28759 28992 I bt_stack: [INFO:gatt_main.cc(1640)] gatt_data_process op_code = 17, msg_len = 13
01-24 13:33:07.811 28759 28992 E bt_stack: [ERROR:gatt_cl.cc(903)] gatt_process_read_by_type_rsp Illegal Response length, must be at least 4.
01-24 13:33:07.814 14949 15488 D BluetoothGatt: onClientConnectionState() - status=0 clientIf=13 device=51:60:83:0D:4B:04
01-24 13:33:07.814 14949 15488 E qaul-blemodule BleActor: onConnectionStateChange: STATE_CONNECTED
01-24 13:33:07.814 14949 15488 E qaul-blemodule BleService:  onConnected : 51:60:83:0D:4B:04
01-24 13:33:07.814 14949 15488 D BluetoothGatt: discoverServices() - device: 51:60:83:0D:4B:04
01-24 13:33:07.814 28759 28839 E bt_btif_gattc: btif_gattc_upstreams_evt: Unhandled event (8)!
01-24 13:33:07.815 28759 28839 D bt_bta_gattc: bta_gattc_get_gatt_db
01-24 13:33:07.815 28759 28839 E bt_stack: [ERROR:bta_gattc_cache.cc(727)] No server cache available
01-24 13:33:07.816 14949 15488 D BluetoothGatt: onSearchComplete() = Device=51:60:83:0D:4B:04 Status=0
01-24 13:33:07.816 14949 15488 E qaul-blemodule BleService:  onDescriptorWrite : 51:60:83:0D:4B:04
01-24 13:33:07.817 14949 15488 D qaul-blemodule BleActor: readServiceData : serUUID : 99E91399-80ED-4943-9BCB-39C532A76023, charUUID:99E91401-80ED-4943-9BCB-39C532A76023
01-24 13:33:07.818 28759 28839 D bt_bta_gattc: bta_gattc_get_gatt_db
01-24 13:33:07.818 28759 28839 E bt_stack: [ERROR:bta_gattc_cache.cc(727)] No server cache available
01-24 13:33:07.819 14949 15488 D BluetoothGatt: onSearchComplete() = Device=51:60:83:0D:4B:04 Status=0
01-24 13:33:07.819 14949 15488 E qaul-blemodule BleService:  onDescriptorWrite : 51:60:83:0D:4B:04
01-24 13:33:07.819 14949 15488 D qaul-blemodule BleActor: readServiceData : serUUID : 99E91399-80ED-4943-9BCB-39C532A76023, charUUID:99E91401-80ED-4943-9BCB-39C532A76023
01-24 13:33:07.824 28759 28992 I bt_stack: [INFO:gatt_main.cc(1640)] gatt_data_process op_code = 1, msg_len = 4
01-24 13:33:07.824 28759 28992 W bt_stack: [WARNING:gatt_cl.cc(1288)] ATT - clcb already not in use, ignoring response

```

**Comment by MathJud** [comment]
fixed in #569
